missing punctuation
error: expected one of `)`, `,`, `.`, `?`, or an operator, found `;`
  --> src/accounts/jobs/odd_registration_attempt.rs:45:18
   |
43 |                 model.insert("action_url", format!("{}/accounts/reset/", var("DOMAIN")
   |                             - unclosed delimiter
44 |                         .expect("DOMAIN not set?")
45 |                 );
   |                  ^ help: `)` may belong here

error: expected one of `!`, `.`, `::`, `;`, `?`, `{`, `}`, or an operator, found `)`
  --> src/accounts/jobs/odd_registration_attempt.rs:47:13
   |
46 |                 model
   |                      - expected one of 8 possible tokens
47 |             });
   |             ^ unexpected token

error: aborting due to 2 previous errors